server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8091/eureka}
  instance:
    hostname: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-catalog-service
          uri: lb://ms-catalog-service
          predicates:
            - Path=/category/**
        - id: ms-order-service
          uri: lb://ms-order-service
          predicates:
            - Path=/order/**
        - id: ms-client-service
          uri: lb://ms-client-service
          predicates:
            - Path=/client/**
